import set from "lodash/fp/set";

const initialState = {
    name: "Autogenerated match",
    playerCount: "1v1",
    roundCount: 5
};

export default (state = initialState, action) => {
    switch (action.type) {
        case "match-creator_name-change":
            return set("name", action.name)(state);
        case "match-creator_round-count-change":
            return set("roundCount", action.roundCount)(state);
        case "match-creator_player-count-change":
            return set("playerCount", action.playerCount)(state);
        default:
            return state;
    }
};